name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          # install essential packages: platform-tools, android platform 33, build-tools 33.0.2
          packages: "platform-tools platforms;android-33 build-tools;33.0.2"

      - name: Setup Gradle (install Gradle if wrapper missing)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.5'

      - name: Build Debug APK (run gradle; wrapper if present will be used)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            echo "Using gradle wrapper"
            ./gradlew assembleDebug --no-daemon
          else
            echo "No gradlew found — using installed gradle"
            gradle assembleDebug --no-daemon
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
